stages:
  - build
  - deploy

build:
  stage: build
  image: node
  before_script:
    - npm install
  script:
    - npm run build
  artifacts:
    paths:
      - dist

deploy:
  stage: deploy
  image:
    name: helgejs/netlify-cli
    entrypoint: [""]
  script:
    - echo "Deploying site to Netlify"
    - netlify deploy --auth=$netlifyToken --dir=dist --site=0315c5b3-bb75-4095-aaae-3e77ceae5541 --prod --message="$CI_COMMIT_MESSAGE"
  artifacts:
    paths:
      - dist
  only:
    - master
